package RDFLibrary;
/* CVS $Id: $ */
 
import org.apache.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from Litera.rdf 
 * @author Auto-generated by schemagen on 10 Jan 2020 15:02 
 */
public class Litera {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://example.org/lit#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    /** <p>The name the author</p> */
    public static final Property authorName = M_MODEL.createProperty( "http://example.org/lit#authorName" );
    
    /** <p>The name of the book</p> */
    public static final Property bookName = M_MODEL.createProperty( "http://example.org/lit#bookName" );
    
    /** <p>The Author works as a translator</p> */
    public static final Property hasTranslated = M_MODEL.createProperty( "http://example.org/lit#hasTranslated" );
    
    /** <p>A book written by the author</p> */
    public static final Property hasWritten = M_MODEL.createProperty( "http://example.org/lit#hasWritten" );
    
    /** <p>A place where a person lives</p> */
    public static final Property livesIn = M_MODEL.createProperty( "http://example.org/lit#livesIn" );
    
}
